services:
  # The Laravel application container
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - vite
      - db
    command: >
      sh -c "
        php artisan migrate --force &&
        php-fpm
      "

  # The Vite build container
  vite:
    image: node:18-alpine
    container_name: laravel-vite
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    environment:
      - APP_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

  # The web server container (Nginx)
  web:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # The MySQL database container
  db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local